# Generated by Django 4.0.3 on 2022-03-27 18:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('ingredients_list', models.TextField()),
                ('body_text', models.TextField()),
                ('posted_date', models.DateTimeField(default=datetime.datetime(2022, 3, 27, 13, 14, 9, 833577))),
                ('edited_date', models.DateTimeField(default=datetime.datetime(2022, 3, 27, 13, 14, 9, 833588))),
                ('parent_recipe', models.IntegerField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
