# Generated by Django 4.0.3 on 2022-03-28 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='edited_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 21, 15, 1, 711051)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 21, 15, 1, 711039)),
        ),
    ]
