# Generated by Django 4.0.3 on 2022-04-02 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_recipe_picture_alter_recipe_edited_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='edited_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 13, 2, 15, 913268)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.FileField(null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 13, 2, 15, 913258)),
        ),
    ]
