# Generated by Django 4.0.3 on 2022-04-02 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_recipe_edited_date_alter_recipe_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='edited_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 13, 10, 52, 565334)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 13, 10, 52, 565323)),
        ),
    ]
