# Generated by Django 4.0.3 on 2022-04-10 15:59

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_recipe_edited_date_alter_recipe_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorites',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='edited_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 11, 59, 17, 577226)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 11, 59, 17, 577226)),
        ),
    ]
