# Generated by Django 4.0.3 on 2022-04-12 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_recipe_edited_date_alter_recipe_posted_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='edited_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 12, 10, 35, 47, 779055)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 12, 10, 35, 47, 779044)),
        ),
    ]
