# Generated by Django 4.0.3 on 2022-04-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_recipe_edited_date_alter_recipe_picture_and_more'),
        ('main', '0010_alter_comment_edited_date_alter_recipe_edited_date_and_more'),
    ]

    operations = [
    ]
