# Generated by Django 4.0.3 on 2022-05-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_merge_20220416_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='deleted',
            field=models.TextField(default='false'),
        ),
    ]
